# Generated by Django 4.1.2 on 2023-05-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='pname',
        ),
    ]
