# Generated by Django 4.1.2 on 2023-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_item_brandname_item_price_alter_item_describe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='Juice', max_length=30)),
                ('pprice', models.CharField(default='30', max_length=30)),
                ('date', models.CharField(default='1/2/3', max_length=30)),
            ],
        ),
    ]
