# Generated by Django 4.1.2 on 2023-05-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='pprice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
